name: Greetings

on: [pull_request, issues]

jobs:
   greeting:
      runs-on: ubuntu-latest
      permissions:
         issues: write
         pull-requests: write
      steps:
         - uses: actions/first-interaction@v1
           with:
              repo-token: ${{ secrets.ACTION_TOKEN }}
              issue-message: 'Thanks for your first issue! Stay tuned. We will reply you immediently.'
              pr-message: 'Thanks for contributing on this repo!'
